font_family      MonoLisa Regular
bold_font        MonoLisa Bold
italic_font      MonoLisa Regular Italic
bold_italic_font MonoLisa Bold Italic
font_size 12

adjust_line_height  0
adjust_column_width 0

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

disable_ligatures never
font_features +zero +onum

scrollback_lines 20000

detect_urls yes
url_color #0087bd
url_style curly
open_url_with default

enable_audio_bell no

remember_window_size  yes
initial_window_width  640
initial_window_height 400
placement_strategy center

tab_bar_style powerline
tab_powerline_style round
active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal
tab_bar_background none

editor nvim

# tiles

map ctrl+" launch --location=hsplit
map ctrl+shift+5 launch --location=vsplit
# map F7 layout_action rotate # rotate split

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

map ctrl+shift+h resize_window narrower
map ctrl+shift+l resize_window wider
map ctrl+shift+k resize_window taller
map ctrl+shift+j resize_window shorter

# theme

# One Dark by Giuseppe Cesarano, https://github.com/GiuseppeCesarano
# This work is licensed under the terms of the GPL-2.0 license.
# For a copy, see https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html.

foreground #979eab
background #282c34
cursor #cccccc
color0 #282c34
color1 #e06c75
color2 #98c379
color3 #e5c07b
color4 #61afef
color5 #be5046
color6 #56b6c2
color7 #979eab
color8 #393e48
color9 #d19a66
color10 #56b6c2
color11 #e5c07b
color12 #61afef
color13 #be5046
color14 #56b6c2
color15 #abb2bf
selection_foreground #282c34
selection_background #979eab

# end-of theme

