" >>> Install themes
" Plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }
" Plug 'romainl/flattened'
Plug 'mhartington/oceanic-next'
" Plug 'sainnhe/edge'
" Plug 'sainnhe/vim-color-forest-night'
" Plug 'arzg/vim-corvine'
" Plug 'rakr/vim-one'
" Plug 'rakr/vim-two-firewatch'
" Plug 'cocopon/iceberg.vim/'
" Plug 'jdkanani/vim-material-theme'
Plug 'hzchirs/vim-material'
" Plug 'herrbischoff/cobalt2.vim'
" Plug 'ajh17/Spacegray.vim'
" Plug 'kristijanhusak/vim-hybrid-material'
