require "user.plugins"
require "user.options"
require "user.treesitter"
require "user.lsp"
require "user.lsp.null-ls"
-- require "user.bufferline"
require "user.lualine"
-- require "user.nerdtree"
require "user.auto"
require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
-- require "user.gitsigns"
require "user.highlight"
require "user.impatient"
require "user.indentline"
require "user.keymaps"
require "user.nvim-tree"
require "user.telescope"
-- require "user.whichkey"
