# export PATH="/usr/local/opt/ncurses/bin:$PATH"
# export PATH="/usr/local/bin:$PATH"
# export PATH="/usr/local/opt/gettext/bin:$PATH"
# export PATH="/usr/local/opt/sqlite/bin:$PATH"
# export PATH="/usr/local/opt/gettext/bin:$PATH"
# export PATH="$HOME/.daml/bin:$PATH"
# export PATH="$HOME/.rbenv/shims/:$PATH"
# export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
# export PATH="$HOME/.cargo/bin:$PATH"
# export PATH="/Users/dmelnikov/bin:$PATH"
# export PATH="$HOME/Library/Application Support/Coursier/bin:$PATH"
# export PATH="/usr/local/lib/ruby/gems/3.1.0/bin:$PATH"
# export PATH="/usr/local/opt/ruby/bin:$PATH"
# export PNPM_PATH="/Users/dmelnikov/Library/pnpm"
# export JAVA_HOME=/usr/local/opt/openjdk@11

# export LDFLAGS="-L/usr/local/opt/sqlite/lib"
# export CPPFLAGS="-I/usr/local/opt/sqlite/include"
# export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
# export LDFLAGS="-L/usr/local/opt/readline/lib"
# export CPPFLAGS="-I/usr/local/opt/readline/include"
# export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"
# export LDFLAGS="-L/usr/local/opt/zlib/lib"
# export CPPFLAGS="-I/usr/local/opt/zlib/include"
source $HOME/.cargo/env
export PATH="$HOME/.fnm:$PATH"
