alias kod='cd ~/code'
# alias tpg='open vscode://file/Users/dmelnikov/code/playgrounds/ts'
alias reqn='cd ~/code/reqpay-develop'
alias reqo='cd ~/code/reqpay-old-ui'
alias pts='cd ~/code/playgrounds/ts'
